#!/usr/bin/env bash

test_description='xapers.'

. ./test-lib.sh

################################################################

# FIXME: add test for source2bib
# FIXME: add test for scandoc

test_expect_code 1 'search error without database' \
    'xapers search tag:foo'

test_expect_success 'import file without source (foo)' \
    'xapers import \
    --file=$DOC_DIR/2007NJPh....9...17L.pdf \
    --tags=new,foo'

test_expect_success 'docdir exists' \
    'test -d $XAPERS_ROOT'

test_begin_subtest 'tag file exists'
cat <<EOF >EXPECTED
foo
new
EOF
test_expect_equal_file "$XAPERS_ROOT"/0000000001/tags EXPECTED

# FIXME: add with prompting
test_expect_success 'import file with source (bar)' \
    'xapers import \
    --file=$DOC_DIR/josaa-29-10-2092-1.pdf \
    --source=$DOC_DIR/josaa-29-10-2092-1.bib \
    --tags=new,bar'

test_begin_subtest 'bib file exists'
cat <<EOF >EXPECTED
@article{
    Izumi_Arai_Barr_Betzwieser_Brooks_Dahl_Doravari_Driggers_Korth_Miao_et_al._2012,
    author = "Izumi, Kiwamu and Arai, Koji and Barr, Bryan and Betzwieser, Joseph and Brooks, Aidan and Dahl, Katrin and Doravari, Suresh and Driggers, Jennifer C. and Korth, W. Zach and Miao, Haixing and et al.",
    publisher = "Optical Society of America",
    doi = "10.1364/JOSAA.29.002092",
    title = "Multicolor cavity metrology",
    url = "http://dx.doi.org/10.1364/JOSAA.29.002092",
    journal = "Journal of the Optical Society of America A",
    number = "10",
    month = "Sep",
    volume = "29",
    year = "2012",
    pages = "2092"
}

EOF
test_expect_equal_file "$XAPERS_ROOT"/0000000002/bibtex EXPECTED

test_expect_success 'update doc with bib (foo)' \
    'xapers update \
    --source=$DOC_DIR/2007NJPh....9...17L.bib \
    id:1'

test_expect_code 1 'import non-existant file' \
    'xapers import --file=foo.pdf'

# FIXME: add test for adding file already in db?

test_begin_subtest 'count all'
output=`xapers count`
test_expect_equal "$output" 2

test_begin_subtest 'count all (*)'
output=`xapers count '*'`
test_expect_equal "$output" 2

test_begin_subtest 'search all'
xapers search '*' >OUTPUT
cat <<EOF >EXPECTED
id:2 [doi:10.1364/JOSAA.29.002092] (bar new) "Multicolor cavity metrology"
id:1 [] (foo new) "Creation of the universe with a stealth scalar field"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search all, limit 1'
xapers search --limit=1 '*' >OUTPUT
cat <<EOF >EXPECTED
id:2 [doi:10.1364/JOSAA.29.002092] (bar new) "Multicolor cavity metrology"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search by id:'
xapers search id:2 >OUTPUT
cat <<EOF >EXPECTED
id:2 [doi:10.1364/JOSAA.29.002092] (bar new) "Multicolor cavity metrology"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search by tag:'
xapers search tag:foo >OUTPUT
cat <<EOF >EXPECTED
id:1 [] (foo new) "Creation of the universe with a stealth scalar field"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search output tags'
xapers search --output=tags tag:foo | sort >OUTPUT
cat <<EOF >EXPECTED
foo
new
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search output tags (*)'
xapers search --output=tags '*' | sort >OUTPUT
cat <<EOF >EXPECTED
bar
foo
new
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search output sources'
xapers search --output=sources '*' >OUTPUT
cat <<EOF >EXPECTED
doi
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'search output files'
xapers search --output=files '*' | sed "s|$XAPERS_ROOT|XAPERS_ROOT|" >OUTPUT
cat <<EOF >EXPECTED
XAPERS_ROOT/0000000002/josaa-29-10-2092-1.pdf
XAPERS_ROOT/0000000001/2007NJPh....9...17L.pdf
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'output bibtex (foo)'
xapers search --output=bibtex tag:foo >OUTPUT
cat <<EOF >EXPECTED
@article{
    arxiv:1234,
    author = "Maeda, Hideki and Maeda, Kei-ichi",
    source = "arxiv",
    title = "Creation of the universe with a stealth scalar field",
    year = "2012",
    sid = "1234"
}

EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'output bibtex (new)'
xapers search --output=bibtex tag:new >OUTPUT
cat <<EOF >EXPECTED
@article{
    Izumi_Arai_Barr_Betzwieser_Brooks_Dahl_Doravari_Driggers_Korth_Miao_et_al._2012,
    author = "Izumi, Kiwamu and Arai, Koji and Barr, Bryan and Betzwieser, Joseph and Brooks, Aidan and Dahl, Katrin and Doravari, Suresh and Driggers, Jennifer C. and Korth, W. Zach and Miao, Haixing and et al.",
    publisher = "Optical Society of America",
    doi = "10.1364/JOSAA.29.002092",
    title = "Multicolor cavity metrology",
    url = "http://dx.doi.org/10.1364/JOSAA.29.002092",
    journal = "Journal of the Optical Society of America A",
    number = "10",
    month = "Sep",
    volume = "29",
    year = "2012",
    pages = "2092"
}

@article{
    arxiv:1234,
    author = "Maeda, Hideki and Maeda, Kei-ichi",
    source = "arxiv",
    title = "Creation of the universe with a stealth scalar field",
    year = "2012",
    sid = "1234"
}

EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'add tag'
xapers tag +qux -- tag:foo
xapers search tag:qux >OUTPUT
cat <<EOF >EXPECTED
id:1 [] (foo new qux) "Creation of the universe with a stealth scalar field"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'check tags added to tag file'
cat <<EOF >EXPECTED
foo
new
qux
EOF
test_expect_equal_file "$XAPERS_ROOT"/0000000001/tags EXPECTED

test_begin_subtest 'remove tag'
xapers tag -qux -- tag:qux
xapers search tag:qux >OUTPUT
cat <<EOF >EXPECTED
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'check tags removed from tag file'
cat <<EOF >EXPECTED
foo
new
EOF
test_expect_equal_file "$XAPERS_ROOT"/0000000001/tags EXPECTED

test_begin_subtest 'export documents'
xapers export "$TMP_DIRECTORY"/export '*'
find "$TMP_DIRECTORY"/export -mindepth 1 | sed "s|$TMP_DIRECTORY|TMP_DIRECTORY|" >OUTPUT
cat <<EOF >EXPECTED
TMP_DIRECTORY/export/Creation_of_the_universe_with_a_stealth_scalar_field.pdf
TMP_DIRECTORY/export/Multicolor_cavity_metrology.pdf
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'restore to existing database'
xapers restore
xapers search '*' >OUTPUT
cat <<EOF >EXPECTED
id:2 [doi:10.1364/JOSAA.29.002092] (bar new) "Multicolor cavity metrology"
id:1 [] (foo new) "Creation of the universe with a stealth scalar field"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'restore purged database'
rm -rf "$XAPERS_ROOT"/.xapers
xapers restore
xapers search '*' >OUTPUT
cat <<EOF >EXPECTED
id:2 [doi:10.1364/JOSAA.29.002092] (bar new) "Multicolor cavity metrology"
id:1 [] (foo new) "Creation of the universe with a stealth scalar field"
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest 'delete document'
echo 'Y' | xapers delete id:1
xapers search id:1 >OUTPUT
cat <<EOF >EXPECTED
EOF
test_expect_equal_file OUTPUT EXPECTED

test_expect_success 'check for deleted docdir' \
    "! test -d $XAPERS_ROOT/0000000001"

################################################################

test_done
