#!/bin/bash

stor=~/documents/xapers

infile="$1"

outdir="$stor"/$(basename "$infile" .pdf)

read -e -p 'save as: ' -i "$outdir" outdir
# while [ -d "$outdir" ] ; do
#     read -e -p 'save as: ' -i "$outdir" outdir
# done

mkdir -p "$outdir"

mv -i "$infile" "$outdir"/pdf

echo "paste bibtex, or C-d to skip:"
bibtex=$(cat)
if [ "$bibtex" ] ; then
    echo "$bibtex" >"$outdir"/bib
fi

(echo xapers new... && xapers new)

read -n 1 -p 'hit key to continue.'
